// examples/angular/src/app/app.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ScrollInfinite, LoadingState } from '@lionforge/scroll-infinite';

interface Photo {
  id: string;
  urls: {
    regular: string;
  };
  alt_description: string | null;
  links: {
    html: string;
  };
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements AfterViewInit, OnDestroy {
  @ViewChild('container') containerElement!: ElementRef<HTMLDivElement>;

  photos: Photo[] = [];
  loading = false;

  private readonly API_KEY = '3KAwY1OxMCAukRvmax3oA2zN6z2SV8R9moYTmwq3N3Y';
  private readonly COUNT = 30;
  private scrollInfinite: ScrollInfinite | null = null;

  ngAfterViewInit() {
    this.initializeScrollInfinite();
  }

  ngOnDestroy() {
    this.scrollInfinite?.destroy();
  }

  private initializeScrollInfinite() {
    this.scrollInfinite = new ScrollInfinite(
      {
        container: this.containerElement.nativeElement,
        threshold: 1000,
        useIntersectionObserver: true,
        rootMargin: '200px',
      },
      {
        onLoadMore: () => this.loadMore(),
        onStateChange: (state) => this.onStateChange(state),
        onError: (error) => this.onError(error),
      }
    );

    this.scrollInfinite.observe();
  }

  async loadMore() {
    console.log('Loading more photos...');
    try {
      const apiUrl = `https://api.unsplash.com/photos/random?client_id=${this.API_KEY}&count=${this.COUNT}`;
      const response = await fetch(apiUrl);
      const newPhotos = await response.json();
      this.photos = [...this.photos, ...newPhotos];
    } catch (error) {
      console.error('Error fetching photos:', error);
      alert('Failed to load more photos. Please try again.');
    }
  }

  onStateChange(state: LoadingState) {
    console.log('State changed:', state);
    this.loading = state === 'loading';
  }

  onError(error: Error) {
    console.error('Error:', error);
    alert('Failed to load more photos. Please try again.');
  }
}

<h1>LionForge ScrollInfinite - Angular Example</h1>
<p class="description">Scroll down to load more images from Unsplash</p>

<div *ngIf="loading" class="loader">
  <img src="/infinity-loader.svg" alt="Loading" />
</div>

<div #container class="image-container">
  <a
    *ngFor="let photo of photos"
    [href]="photo.links.html"
    target="_blank"
    rel="noopener noreferrer"
  >
    <img
      [src]="photo.urls.regular"
      [alt]="photo.alt_description || 'Unsplash photo'"
      [title]="photo.alt_description || 'Unsplash photo'"
    />
  </a>
</div>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { infiniteScroll } from '@lionforge/svelte-scroll-infinite';

  interface Photo {
    id: string;
    urls: {
      regular: string;
    };
    alt_description: string | null;
    links: {
      html: string;
    };
  }

  const API_KEY = '3KAwY1OxMCAukRvmax3oA2zN6z2SV8R9moYTmwq3N3Y';
  const COUNT = 30;

  let photos: Photo[] = [];
  let loading = false;

  async function fetchPhotos(): Promise<Photo[]> {
    const apiUrl = `https://api.unsplash.com/photos/random?client_id=${API_KEY}&count=${COUNT}`;
    const response = await fetch(apiUrl);
    const data = await response.json();
    return data;
  }

  async function loadMore() {
    console.log('Loading more photos...');
    loading = true;
    try {
      const newPhotos = await fetchPhotos();
      photos = [...photos, ...newPhotos];
    } catch (error) {
      console.error('Error:', error);
      alert('Failed to load more photos. Please try again.');
    } finally {
      loading = false;
    }
  }

  function handleStateChange(state: string) {
    console.log('State changed:', state);
    loading = state === 'loading';
  }

  function handleError(error: Error) {
    console.error('Error:', error);
    alert('Failed to load more photos. Please try again.');
  }
</script>

<div>
  <h1>LionForge ScrollInfinite - Svelte Example</h1>
  <p class="description">Scroll down to load more images from Unsplash</p>

  {#if loading}
    <div class="loader">
      <img src="/infinity-loader.svg" alt="Loading" />
    </div>
  {/if}

  <div
    use:infiniteScroll={{
      onLoadMore: loadMore,
      onStateChange: handleStateChange,
      onError: handleError,
      threshold: 1000,
      useIntersectionObserver: true,
      rootMargin: '200px',
    }}
    class="image-container"
  >
    {#each photos as photo (photo.id)}
      <a href={photo.links.html} target="_blank" rel="noopener noreferrer">
        <img
          src={photo.urls.regular}
          alt={photo.alt_description || 'Unsplash photo'}
          title={photo.alt_description || 'Unsplash photo'}
        />
      </a>
    {/each}
  </div>
</div>
